name: Build And Image

on:
  push:
    branches:
      - "v1"
    paths-ignore:
      - "README.md"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Jinlihub
        uses: docker/login-action@v1
        with:
          registry: hub.jinli.plus
          username: ${{ secrets.DOCKER_USERNAME_JINLI }}
          password: ${{ secrets.DOCKER_PASSWORD_JINLI }}

      - name: Login to Github
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GIT_USER }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Login to Aliyun
        uses: docker/login-action@v1
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.DOCKER_USERNAME_ALIYUN }}
          password: ${{ secrets.DOCKER_PASSWORD_ALIYUN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          push: true
          tags: |
            jinlicode/nginx:v1
            hub.jinli.plus/jinlicode/nginx:v1
            ghcr.io/jinlicode/nginx:v1
            registry.cn-beijing.aliyuncs.com/jinlicode/nginx:v1
